# Basic configuration for an ESP32 device
esphome:
  name: melchior-atx
  friendly_name: Melchior ATX 

# Hardware configuration
esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable Home Assistant API
api:

network:
  enable_ipv6: true

# Enable over-the-air updates
ota:
  platform: esphome

# If you want Wifi then uncoment this and create secrets.yaml with wifi_ssid and wifi_password
#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

#web_server:
#  port: 80

openthread:
  tlv: !secret openthread_tlv 

output:
  - platform: gpio
    pin: GPIO18
    id: pwr_out 
    inverted: false
  - platform: gpio
    pin: GPIO20
    id: rst_out 
    inverted: false
  - platform: gpio
    pin: GPIO0
    id: status_out 
    inverted: false

button:
  - platform: output
    name: "Power Button"
    output: pwr_out
    duration: 500ms
    on_press:
      then:
        - output.turn_on: status_out
        - delay: 500ms
        - output.turn_off: status_out
  - platform: output
    name: "Power Button - Long Press"
    output: pwr_out
    duration: 5000ms
    on_press:
      then:
        - output.turn_on: status_out
        - delay: 5000ms
        - output.turn_off: status_out
  - platform: output
    name: "Reset Button"
    output: rst_out
    duration: 500ms
    on_press:
      then:
        - output.turn_on: status_out
        - delay: 100ms
        - output.turn_off: status_out
        - delay: 100ms
        - output.turn_on: status_out
        - delay: 100ms
        - output.turn_off: status_out

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        inverted: true
    name: "Power"
  - platform: gpio
    pin:
      number: GPIO21
      mode:
        input: true
        inverted: true
    name: "Button"

light:
  - platform: status_led
    name: "Status LED"
    output: status_out
